# Generated by Django 3.1.2 on 2020-10-31 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='comleted',
            new_name='completed',
        ),
    ]
